### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by SangaoWe** [JasperZhang121/Vaults#2]
Hey jas, I can help reinforcement learning and some CV.

**Comment by JasperZhang121** [comment]
yeah, sounds good, I just started to focus on Reinforcement learning. And still left some work to do for Deep Learning.

**Comment by SangaoWe** [comment]
will also have a look on DL.

**Comment by JasperZhang121** [comment]
thanks Eric, let me know you back to CBR
