### ISSUE TITLE
Notes for Reinforcement Learning and double check for Deep Learning

### ISSUE THREAD

**Issue by JasperZhang121** [JasperZhang121/Vaults#4]
_I have recently started delving into **reinforcement learning** and have found it to be considerably more complex than previous machine learning and deep learning approaches, due to its heavy reliance on mathematical induction and proof. As such, I will need to spend some time carefully reviewing the formulas and concepts before providing clear explanations and code examples. Unfortunately, my current workload is quite heavy, so this may take some time._

Furthermore, I have not yet had the opportunity to double-check my deep learning work and provide accompanying code examples, which I plan to do at a later time

**Comment by SangaoWe** [comment]
By the way, I noticed that the notes in the CV seem a bit unclear. When you're updating the DL, you might want to take a look at them too to make sure there's no overlap.

Also, the reference links for the graph aren't working properly and some of the formulas are not written well in LaTeX format, just thought I'd give you a heads up on that one.

**Comment by JasperZhang121** [comment]
_Emm, will do that next Month._

**Comment by JasperZhang121** [comment]
_Have revised CNN, but others might take much longer time to document it and check all mathematics. Will try to done it by end of next week._
